books/urls.py
from django.urls import path
from .views import *
from django.conf import settings

app_name="books"
urlpatterns = [
   path('home/', LibHomepage.as_view(), name='home'),
   path('books_list/', BookList.as_view(), name='book_list'),
   path('book_detail/<int:pk>/', BookDetailView.as_view(), name='book_details'),
   path('authors_list/', AuthorList.as_view(), name='author_list'),
   path('author_detail/<int:pk>/', AuthorDetailView.as_view(), name='author_details'),
   path('book/borrow/<int:id>/', BorrowBook, name='borrow_book'),
   path('borrowed_books/', BorrowedBooks.as_view(), name='borrowed_books'),
   path('borrow_history/', BorrowHistory.as_view(), name='borrow_history'),
   path('book/return/<int:id>/', ReturnBook, name='return_book'),
]

dingo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dingo.api import router

urlpatterns = [
   path('jet/', include('jet.urls', 'jet')),
   path('admin/', admin.site.urls),
   path('api/v1/', include(router.urls)),
   path('', include("greetings.urls")),
   path('maths/', include("maths.urls")),
   path('posts/', include("posts.urls")),
   path('members/', include("django.contrib.auth.urls")),
   path('members/', include("members.urls")),
   path('books/', include("books.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

greetings/urls.py
from django.urls import path
from .views import about, contact, welcome

app_name="greetings"
urlpatterns = [
       path('', welcome, name="welcome"),
       path('about/', about, name="about"),
       path('contact/', contact, name="contact"),
]

posts/urls.py
from django.urls import path
from .views import Homepage, PostDetailView, AddPost, EditPost, DeletePost, AuthorList, AuthorDetailView
from django.conf import settings
from django.conf.urls.static import static

app_name="posts"
urlpatterns = [
   path('home/', Homepage.as_view(), name='home'),
   path('post_detail/<int:pk>/', PostDetailView.as_view(), name='post_details'),
   path('add_post/', AddPost.as_view(), name='add_post'),
   path('post/edit/<int:pk>/', EditPost.as_view(), name='edit_post'),
   path('post/delete/<int:pk>/', DeletePost.as_view(), name='delete_post'),
   path('author_list/', AuthorList.as_view(), name='author_list'),
   path('author_detail/<int:pk>/', AuthorDetailView.as_view(), name='author_details'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

COVERS = (
    ("hard", "Twarda okładka" ), 
    ("soft","Miękka okładka")
    )

class Book(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=500, blank=True, null=True)
    cover = models.CharField(max_length=50, choices=COVERS, blank=True, null=True)
    tags = models.ManyToManyField("books.Tag", blank=True)
    image = models.ImageField(null=True, blank=True)
    author = models.ForeignKey(
        'books.Author',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    
    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def get_absolute_url(self):
        return reverse('home')

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    @property
    def is_available(self):
        current_borrow = self.borrow_set.filter(returned=None)
        if current_borrow:
            return "Wypożyczona"
        return "Dostępna"

class Author(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    description = models.TextField(max_length=500, blank=True, null=True)
    image = models.ImageField(null=True, blank=True)

    def __str__ (self):
        return self.first_name + ' ' + self.last_name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class Tag(models.Model):
   word = models.CharField(max_length=50, unique=True)
   created = models.DateTimeField(auto_now_add=True)

   def __str__(self):
        return self.word

class Borrow(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    borrowed = models.DateTimeField(auto_now_add=True)
    returned = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return str(self.book)

books/forms.py
from django import forms
from matplotlib import widgets
from .models import Book

class RentBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['status']

        widgets = {
            'status': forms.Select(attrs={'class': 'form-control'}),
        }

books/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, DeleteView
from books.models import *
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.utils.timezone import now

class LibHomepage(ListView):
    model = Book
    template_name = 'books/home.html'

def all_and_borrowed_books_count(request):
    count_all= Book.objects.all().count()    
    count_borrowed= Borrow.objects.all().count()    
    context= {
        'count_all':count_all,
        'count_borrowed':count_borrowed
        }        
    return render(request, 'books/home.html', context)

class BookList(ListView):
    paginate_by = 3
    model = Book
    template_name = 'books/books_list.html'

class BookDetailView(DetailView):
    model = Book
    template_name = 'books/book_details.html'

class AuthorList(ListView):
    paginate_by = 4
    model = Author
    template_name = 'books/author_list.html'

class AuthorDetailView(DetailView):
    model = Author
    template_name = 'books/author_details.html'

def BorrowBook(request, id):
    book = Book.objects.get(id=id)
    user = request.user
    Borrow.objects.create(book=book, user=user)
    return HttpResponseRedirect(reverse('books:borrowed_books'))

class BorrowedBooks(ListView):
    paginate_by = 3
    model = Borrow
    template_name = 'books/borrowed_books.html'

    def get_queryset(self):
        return Borrow.objects.filter(user=self.request.user).filter(returned=None)

class BorrowHistory(ListView):
    paginate_by = 10
    model = Borrow
    template_name = 'books/borrow_history.html'

    def get_queryset(self):
        return Borrow.objects.filter(user=self.request.user)

def ReturnBook(request, id):
    book = Borrow.objects.get(id=id)
    if book.returned==None:
        book.returned = now()
        book.save()
    return HttpResponseRedirect(reverse("books:borrowed_books"))

books/templates/books/author_details.html
{% extends 'books/base.html' %}
{% block title %}O Autorze{% endblock %}

{% block content %}

<h1>O Autorze</h1>
<br>
<br>
<img class="thumbnail" src="{{ author.imageURL }}" width="auto" height="400">
<br>
Imię: {{ author.first_name }}
<br>
Nazwisko: {{ author.last_name }}
<br>
<br>
{{ author.description }}
<br>
<br>
<h3>Dzieła tego autora dostępne w naszej bibliotece:</h3><br>

{% for book in author.book_set.all %}
    <li>
        <a href="{% url 'books:book_details' book.pk %}">{{ book.title }}</a> 
    </li>
{% endfor %}

<br>
<br>
<a href="{% url 'books:author_list' %}" class="btn btn-primary">Wróć</a>
<br>
<br>

{% endblock %}

books/templates/books/author_list.html
{% extends 'books/base.html' %}
{% block title %}Lista Autorów{% endblock %}

{% block content %}
 
<h1>Lista Naszych Autorów</h1>
<br>
<br>
<div class="row">
    {% for author in object_list %}
        <br>
        <div class="col-lg-4">
            <img class="thumbnail" src="{{ author.imageURL }}" width="auto" height="400">
            <div class="box-element author">
                <h6><strong><a href="{% url 'books:author_details' author.pk %}">{{ author.first_name }} {{ author.last_name }}</a></strong></h6>
            </div>
        </div>
    {% endfor %}
</div>
<br>
<br>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1" class="btn btn-primary">&laquo; Pierwsza</a>
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary">Poprzednia</a>
        {% endif %}

        <span class="current">
            Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary">Następna</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-primary">Ostatnia &raquo;</a>
        {% endif %}
    </span>
</div>
</ul>
<br>
<br>
<a href="{% url 'books:home' %}" class="btn btn-primary">Wróć</a>
<br>
<br>

{% endblock %}

books/templates/books/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>
        {% block title %}
            Biblioteka Online
        {% endblock %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'books:home' %}">BIBLIOTEKA ONLINE</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'books:book_list' %}">Nasze Książki</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'books:author_list' %}">Nasi Autorzy</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'books:borrowed_books' %}">Twoje Książki</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'books:borrow_history' %}">Historia Wypożyczeń</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Nasze Apki
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'posts:home' %}">Posty</a>
                <a class="dropdown-item" href="{% url 'books:home' %}">Biblioteka</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'greetings:welcome' %}">Strona Główna</a>
              </div>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Zaloguj</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Zarejestruj</a>
            </li>
            {% endif %}            
          </ul>
        </div>
        {% if user.is_authenticated %}
        <div>
          <ul class="navbar-nav mr-auto">
            <li>
              <span class="navbar-text">Witaj, {{request.user}} | </span>
            </li>
            <li>
              <span ><a  class="nav-link" href="{% url 'logout' %}">Wyloguj</a></span>
            </li>
          </ul>
        </div>
        {% endif %} 
    </nav>
    <br>
    <br>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

books/templates/books/book_details.html
{% extends 'books/base.html' %}
{% block title %}{{ book.title }}{% endblock %}

{% block content %}

<h1>{{ book.title }}</h1>
<br>
<br>
<img class="thumbnail" src="{{ book.imageURL }}" width="auto" height="400">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<div style="display:inline-block;vertical-align:top;">
    Autorstwa: {{ book.author }} - <a href="{% url 'books:author_details' book.author.pk %}">O Autorze</a>
    <br>
    <br>
    <h4>Opis książki</h4>
    {{ book.description }}
    <br>
    <br>
    Status: {{ book.is_available }}
    <br>
    <br>
    {% if user.is_authenticated %}
        {%  if not book.is_available %}
            <a href="{% url 'books:return_book' book.id %}" class="btn btn-danger">Zwróć</a><br>
        {% else %}
            <div class="form-group" enctype='multipart/form-data'>
                <form action="{% url 'books:borrow_book' book.pk %}" method="POST">
                    {% csrf_token %}
                    <button type="submit", name="book_id", value="{{ book.id }}" class="btn btn-success">Wypożycz</button>
                </form>
            </div>
        {% endif %}
    {% endif %}
</div>
<br>
<br>
<a href="{% url 'books:book_list' %}" class="btn btn-primary">Wróć</a>
<br>
<br>

{% endblock %}

books/templates/books/books_list.html
{% extends 'books/base.html' %}
{% block title %}Lista Książek{% endblock %}
{% load static %}
{% block content %}
 
<h1>Lista Naszych Książek</h1>
<br>
<br>
<div class="row">
    {% for book in object_list %}
        <br>
        <div class="col-lg-4">
            <img class="thumbnail" src="{{ book.imageURL }}" width="auto" height="400">
            <div class="box-element product">
                <h6><strong><a href="{% url 'books:book_details' book.pk %}">{{ book.title }}</a></strong></h6>
                autorstwa: {{ book.author }} 
            </div>
        </div>
    {% endfor %}
</div>
<br>
<br>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1" class="btn btn-primary">&laquo; Pierwsza</a>
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary">Poprzednia</a>
        {% endif %}

        <span class="current">
            Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary">Następna</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-primary">Ostatnia &raquo;</a>
        {% endif %}
    </span>
</div>
<br>
<br>
<a href="{% url 'books:home' %}" class="btn btn-primary">Wróć</a>
<br>
<br>

{% endblock %}

books/templates/books/borrow_history.html
{% extends 'books/base.html' %}

{% block content %}

{% if user.is_authenticated %}
    <h3>Historia Twoich wypożyczeń:</h3>
    <br>
    <br>
    <div>
        {% for book in object_list %}
                <br>
                <div class="col-lg-4">
                    <div class="box-element product">
                        <ul>
                            <li>
                                <h6><strong>Tytuł: {{ book }}</strong></h6>
                                <h6><strong>Data Wypożyczenia: {{ book.borrowed }}</strong></h6>
                                <h6><strong>Data zwrotu: {{ book.returned }}</strong></h6>                                
                            </li>
                        </ul> 
                    </div>
                </div>
        {% endfor %}
    </div>
    <br>
    <br>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1" class="btn btn-primary">&laquo; Pierwsza</a>
                <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary">Poprzednia</a>
            {% endif %}

            <span class="current">
                Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary">Następna</a>
                <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-primary">Ostatnia &raquo;</a>
            {% endif %}
        </span>
    </div>
{% else %}
    Nie jesteś zalogowany!
    <a class="nav-link" href="{% url 'login' %}" class="btn btn-primary">Zaloguj się</a>
{% endif %}
<br>
<br>
<a href="{% url 'books:home' %}" class="btn btn-primary">Wróć</a>
<br>
<br>

{% endblock %}

books/templates/books/borrowed_books.html
{% extends 'books/base.html' %}

{% block content %}

{% if user.is_authenticated %}
    <h3>Wypożyczone przez Ciebie książki:</h3>
    <br>
    <br>
    <div class="row">
        {% for book in object_list %}
            {% if not book.returned %}
                <br>
                <div class="col-lg-4">
                    <img class="thumbnail" src="{{ book.book.imageURL }}" width="auto" height="400">
                    <div class="box-element product">
                        <h6><strong><a href="{% url 'books:book_details' book.pk %}">{{ book }}</a></strong></h6>
                        Data Wypożyczenia: {{ book.borrowed }}
                        <a href="{% url 'books:return_book' book.id %}" class="btn btn-danger">Zwróć</a><br> 
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <br>
    <br>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1" class="btn btn-primary">&laquo; Pierwsza</a>
                <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary">Poprzednia</a>
            {% endif %}

            <span class="current">
                Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary">Następna</a>
                <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-primary">Ostatnia &raquo;</a>
            {% endif %}
        </span>
    </div>
{% else %}
    Nie jesteś zalogowany!
    <a class="nav-link" href="{% url 'login' %}" class="btn btn-primary">Zaloguj się</a>
{% endif %}
<br>
<br>
<a href="{% url 'books:home' %}" class="btn btn-primary">Wróć</a>
<br>
<br>

{% endblock %}

books/templates/books/home.html
{% extends 'books/base.html' %}
{% block title %}Home{% endblock %}

{% load static %}

{% block content %}
 
<center><h1>Witaj w naszej Bibliotece Internetowej!</h1></center>
<br>
<center><h3>Nowoczesnej wypożyczalni książek online!</h3></center>
<br>
<div>
    <img src="{% static 'books/static/img/home.jpg' %}" width="1100" height="auto">
</div>
<br>
<br>
<center><strong>Liczba wszystkich książek w naszej bibliotece: {{ count_all }}</strong></center>
<center><strong>Liczba wypożyczonych książek w naszej bibliotece: {{ count_borrowed }}</strong></center>
<br>
<br>
<br>
<br>
{% endblock %}

books/templates/books/return_book.html
{% extends 'books/base.html' %}
{% block title %}Return Book{% endblock %}

{% block content %}
 
{% if user.is_authenticated %}

    <h3>Oddajesz: {{ borrow.book }}</h3>

    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            <strong>Napewno chcesz zwrócić ten tytuł?</strong><br><br>
            <button type="submit", name="book_id", value="{{ book.id }}" class="btn btn-danger">Tak</button>
            <a href="{% url 'books:borrowed_books' %}" class="btn btn-success">Nie</a>
        </form>
    </div>
{% else %}
    Nie jesteś zalogowany!
    <a class="nav-link" href="{% url 'login' %}" class="btn btn-primary">Zaloguj się</a>
{% endif %}

{% endblock %}