books/urls.py
from django.urls import path
from .views import *
from django.conf import settings

app_name="books"
urlpatterns = [
   path('home/', LibHomepage.as_view(), name='home'),
   path('books_list/', BookList.as_view(), name='book_list'),
   path('book_detail/<int:pk>/', BookDetailView.as_view(), name='book_details'),
   path('authors_list/', AuthorList.as_view(), name='author_list'),
   path('author_detail/<int:pk>/', AuthorDetailView.as_view(), name='author_details'),
   path('book/borrow/<int:id>/', BorrowBook, name='borrow_book'),
   path('borrowed_books/', BorrowedBooks.as_view(), name='borrowed_books'),
   path('borrow_history/', BorrowHistory.as_view(), name='borrow_history'),
   path('book/return/<int:id>/', ReturnBook, name='return_book'),
]

dingo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dingo.api import router

urlpatterns = [
   path('jet/', include('jet.urls', 'jet')),
   path('admin/', admin.site.urls),
   path('api/v1/', include(router.urls)),
   path('', include("greetings.urls")),
   path('maths/', include("maths.urls")),
   path('posts/', include("posts.urls")),
   path('members/', include("django.contrib.auth.urls")),
   path('members/', include("members.urls")),
   path('books/', include("books.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

greetings/urls.py
from django.urls import path
from .views import about, contact, welcome

app_name="greetings"
urlpatterns = [
       path('', welcome, name="welcome"),
       path('about/', about, name="about"),
       path('contact/', contact, name="contact"),
]

posts/urls.py
from django.urls import path
from .views import Homepage, PostDetailView, AddPost, EditPost, DeletePost, AuthorList, AuthorDetailView
from django.conf import settings
from django.conf.urls.static import static

app_name="posts"
urlpatterns = [
   path('home/', Homepage.as_view(), name='home'),
   path('post_detail/<int:pk>/', PostDetailView.as_view(), name='post_details'),
   path('add_post/', AddPost.as_view(), name='add_post'),
   path('post/edit/<int:pk>/', EditPost.as_view(), name='edit_post'),
   path('post/delete/<int:pk>/', DeletePost.as_view(), name='delete_post'),
   path('author_list/', AuthorList.as_view(), name='author_list'),
   path('author_detail/<int:pk>/', AuthorDetailView.as_view(), name='author_details'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

greetings/models.py
from django.db import models

# Create your models here.

greetings/views.py
from django.shortcuts import render
from django.http import HttpResponse

def welcome(request):
    return render(request, 'greetings/welcome.html')

def about(request):
    return HttpResponse('Coś o stronie...')

def contact(request):
    return HttpResponse('Napisz do nas!')

greetings/templates/greetings/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <title>{% block title %}Witamy!{% endblock %}</title>

   {% load static %}

   {# Load CSS and JavaScript #}
   {% bootstrap_css %}
   {% bootstrap_javascript jquery='full' %}

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'greetings:welcome' %}">DINGO</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'greetings:about' %}">O nas</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Nasze Apki
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'posts:home' %}">Posty</a>
            <a class="dropdown-item" href="{% url 'books:home' %}">Biblioteka</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'greetings:contact' %}">Kontakt</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Zaloguj</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Zarejestruj</a>
        </li>
        {% endif %}            
      </ul>
    </div>
    {% if user.is_authenticated %}
    <div>
      <ul class="navbar-nav mr-auto">
        <li>
          <span class="navbar-text">Witaj, {{request.user}} | </span>
        </li>
        <li>
          <span ><a  class="nav-link" href="{% url 'logout' %}">Wyloguj</a></span>
        </li>
      </ul>
    </div>
    {% endif %} 
</nav>
<br>
<br>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

greetings/templates/greetings/welcome.html
{% extends 'greetings/base.html' %}
{% block title %}Home{% endblock %}

{% load static %}

{% block content %}

<center><h1>DINGO</h1></center>
<center><h4>Witaj na Stronie Głównej DINGO!</h4></center>
<br>
<div>
    <img src="{% static 'greetings/static/img/dingo.jpg' %}" width="1100" height="auto">
</div>
<br>
<br>
<br>

{% endblock %}