books/urls.py
from django.urls import path
from .views import *
from django.conf import settings

app_name="books"
urlpatterns = [
   path('home/', LibHomepage.as_view(), name='home'),
   path('books_list/', BookList.as_view(), name='book_list'),
   path('book_detail/<int:pk>/', BookDetailView.as_view(), name='book_details'),
   path('authors_list/', AuthorList.as_view(), name='author_list'),
   path('author_detail/<int:pk>/', AuthorDetailView.as_view(), name='author_details'),
   path('book/borrow/<int:id>/', BorrowBook, name='borrow_book'),
   path('borrowed_books/', BorrowedBooks.as_view(), name='borrowed_books'),
   path('borrow_history/', BorrowHistory.as_view(), name='borrow_history'),
   path('book/return/<int:id>/', ReturnBook, name='return_book'),
]

dingo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dingo.api import router

urlpatterns = [
   path('jet/', include('jet.urls', 'jet')),
   path('admin/', admin.site.urls),
   path('api/v1/', include(router.urls)),
   path('', include("greetings.urls")),
   path('maths/', include("maths.urls")),
   path('posts/', include("posts.urls")),
   path('members/', include("django.contrib.auth.urls")),
   path('members/', include("members.urls")),
   path('books/', include("books.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

greetings/urls.py
from django.urls import path
from .views import about, contact, welcome

app_name="greetings"
urlpatterns = [
       path('', welcome, name="welcome"),
       path('about/', about, name="about"),
       path('contact/', contact, name="contact"),
]

posts/urls.py
from django.urls import path
from .views import Homepage, PostDetailView, AddPost, EditPost, DeletePost, AuthorList, AuthorDetailView
from django.conf import settings
from django.conf.urls.static import static

app_name="posts"
urlpatterns = [
   path('home/', Homepage.as_view(), name='home'),
   path('post_detail/<int:pk>/', PostDetailView.as_view(), name='post_details'),
   path('add_post/', AddPost.as_view(), name='add_post'),
   path('post/edit/<int:pk>/', EditPost.as_view(), name='edit_post'),
   path('post/delete/<int:pk>/', DeletePost.as_view(), name='delete_post'),
   path('author_list/', AuthorList.as_view(), name='author_list'),
   path('author_detail/<int:pk>/', AuthorDetailView.as_view(), name='author_details'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    tags = models.ManyToManyField("posts.Tag")
    author = models.ForeignKey(
        'posts.Author',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    
    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def get_absolute_url(self):
        return reverse('home')

class Author(models.Model):
    nick = models.CharField(max_length=50, blank=True, null=True, unique=True)
    email = models.EmailField(
        max_length=255,
        unique=True
    )
    def __str__ (self):
        return self.nick

class Tag(models.Model):
   word = models.CharField(max_length=50, unique=True)
   created = models.DateTimeField(auto_now_add=True)

posts/forms.py
from django import forms
from matplotlib import widgets
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        fields = ["title", "content", "author", "image"]

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'})
        }

class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'})
        }

posts/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from posts.models import Post, Author
from posts.forms import PostForm, EditForm
from django.urls import reverse_lazy

#def home(request):
#    return render(request, 'home.html', {})

class Homepage(ListView):
    model = Post
    template_name = 'posts/home.html'
    ordering = ['-modified']

class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/post_details.html'

class AddPost(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/add_post.html'
    #fields = '__all__'

class EditPost(UpdateView):
    model = Post
    form_class = EditForm
    template_name = 'posts/update_post.html'

class DeletePost(DeleteView):
    model = Post
    template_name = 'posts/delete_post.html'
    success_url = reverse_lazy('home')

class AuthorList(ListView):
    model = Author
    template_name = 'posts/author_list.html'

class AuthorDetailView(DetailView):
    model = Author
    template_name = 'posts/author_details.html'

posts/templates/posts/add_post.html
{% extends 'posts/base.html' %}
{% block title %}Create a new Post!{% endblock %}

{% block content %}
 
{% if user.is_authenticated %}
<h1>Add Post</h1>

<div class="form-group" enctype='multipart/form-data'>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary">Post</button>
    </form>
</div>
{% else %}
You can't do that!

{% endif %}

{% endblock %}

posts/templates/posts/author_details.html
{% extends 'posts/base.html' %}
{% block title %}Author Details{% endblock %}

{% block content %}

<h1>Author Details</h1>
<small>
    Nick: {{ author.nick }}<br>
    Email: {{ author.email }}
</small>
<br>
<br>
<a href="{% url 'posts:author_list' %}" class="btn btn-primary">Back</a>

{% endblock %}

posts/templates/posts/author_list.html
{% extends 'posts/base.html' %}
{% block title %}List of Authors{% endblock %}

{% block content %}
 
<h1>List of Authors</h1>

<ul>
{% for author in object_list %}
    <li>
        <a href="{% url 'posts:author_details' author.pk %}">{{ author.nick }}</a> 
    </li>
{% endfor %}
</ul>
<br>
<br>
<a href="{% url 'posts:home' %}" class="btn btn-primary">Back</a>

{% endblock %}

posts/templates/posts/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>
        {% block title %}
            Posts Page
        {% endblock %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'posts:home' %}">POSTY</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'posts:add_post' %}">Dodaj Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'posts:author_list' %}">Autorzy</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Nasze Apki
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'posts:home' %}">Posty</a>
                <a class="dropdown-item" href="{% url 'books:home' %}">Biblioteka</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'greetings:welcome' %}">Strona Główna</a>
              </div>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Zaloguj</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Zarejestruj</a>
            </li>
            {% endif %}
          </ul>
        </div>
            {% if user.is_authenticated %}
            <div>
              <ul class="navbar-nav mr-auto">
                <li>
                    <span class="navbar-text">Witaj, {{request.user}} | </span>
                </li>
                <li>
                    <span ><a  class="nav-link" href="{% url 'logout' %}">Wyloguj</a></span>
                </li>
              </ul>
            </div>
        {% endif %}             
      </nav>
    <br>
    <br>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

posts/templates/posts/delete_post.html
{% extends 'posts/base.html' %}
{% block title %}Delete Post!{% endblock %}

{% block content %}
 
{% if user.is_authenticated %}
<h1>Delete Post</h1>
<br>
<br>
<h3>Delete: {{ post.title }}</h3>

<div class="form-group">
    <form method="POST">
        {% csrf_token %}
        <strong>Are you sure?</strong><br><br>
        <button class="btn btn-primary">Delete</button>
    </form>
</div>
{% else %}
You can't do that!

{% endif %}

{% endblock %}

posts/templates/posts/home.html
{% extends 'posts/base.html' %}
{% block title %}Home{% endblock %}

{% block content %}
 
<h1>Posts</h1>

<ul>
{% for post in object_list %}
    <li><a href="{% url 'posts:post_details' post.pk %}">{{ post.title }}</a> by {{ post.author }}  -  
        {% if user.is_authenticated %}
        <a href="{% url 'posts:author_details' post.author.pk %}">Details of Author</a>  -  <a href="{% url 'posts:edit_post' post.pk %}" class="btn btn-primary">Edit</a>  -  <a href="{% url 'posts:delete_post' post.pk %}" class="btn btn-primary">Delete</a><br>
        {% endif %}
        {{ post.content }}
    </li>
{% endfor %}
</ul>

{% endblock %}

posts/templates/posts/post_details.html
{% extends 'posts/base.html' %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}

<h1>{{ post.title }}</h1>
<small>By: {{ post.author }}  -  Created:{{ post.created }}  -  Modified:{{ post.modified }} | 
{% if user.is_authenticated %}
<a href="{% url 'posts:edit_post' post.pk %}" class="btn btn-primary">Edit</a><a href="{% url 'posts:delete_post' post.pk %}" class="btn btn-primary">Delete</a></small>
{% endif %}
<br>
<hr>
<br>
{{ post.content }}
<br>
<br>
<div><img src="{{ post.image.url }}"></div>
<br>
<br>
<a href="{% url 'posts:home' %}" class="btn btn-primary">Back</a>

{% endblock %}

posts/templates/posts/update_post.html
{% extends 'posts/base.html' %}
{% block title %}Edit Post!{% endblock %}

{% block content %}

{% if user.is_authenticated %}
<h1>Edit Post</h1>

<div class="form-group">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary">Update</button>
    </form>
</div>

{% else %}
You can't do that!

{% endif %}

{% endblock %}